"use client";

import * as React from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { MasteryEngine } from "@/lib/mastery/engine";
import { AssessmentEvidence } from "@/lib/mastery/types";
import { ChemistryLearningEvidence } from "@/lib/chemistry/types";
import { ORGANIC_CHEMISTRY_TOPIC_PLAN } from "@/lib/chemistry/organic-chemistry-demo";
import { CarbonAtomVisualizer } from "@/components/chemistry/carbon-atom-visualizer";
import { CarbonBondBuilder } from "@/components/chemistry/carbon-bond-builder";
import { BondOrderVisualizer } from "@/components/chemistry/bond-order-visualizer";
import { HybridizationVisualizer } from "@/components/chemistry/hybridization-visualizer";
import { MoleculeBuilder } from "@/components/chemistry/molecule-builder";
import {
  ArrowLeft,
  Atom,
  Link2,
  SplitSquareVertical,
  Compass,
  Hammer,
  Trophy,
  ChevronRight,
  ShieldCheck,
  BrainCircuit,
} from "lucide-react";

interface VisualLearningWorkspaceProps {
  onBackToTopicPlan?: () => void;
  onStageCompleted?: (stageNumber: number, masteryScore: number) => void;
}

export function VisualLearningWorkspace({
  onBackToTopicPlan,
  onStageCompleted,
}: VisualLearningWorkspaceProps) {
  // Active concept tab in Stage 1
  const [activeConceptId, setActiveConceptId] = React.useState<string>("c-org-1");

  // Local instance of KEA Deterministic Mastery Engine (W-EMM) initialized once
  const [masteryEngine] = React.useState<MasteryEngine>(() => new MasteryEngine());

  // Concept scores state tracked across the 5 Stage 1 concepts
  const [conceptScores, setConceptScores] = React.useState<Record<string, number>>({
    "c-org-1": 0,
    "c-org-2": 0,
    "c-org-3": 0,
    "c-org-4": 0,
    "c-org-5": 0,
  });

  const [evidenceLog, setEvidenceLog] = React.useState<
    Array<{
      conceptId: string;
      activityTitle: string;
      score: number;
      timestamp: number;
      deltaText: string;
    }>
  >([]);

  // Calculate average stage mastery
  const stage1Concepts = ORGANIC_CHEMISTRY_TOPIC_PLAN.stages[0].concepts;
  const currentTotalScore = Object.values(conceptScores).reduce((a, b) => a + b, 0);
  const averageStageMastery = Math.round(currentTotalScore / stage1Concepts.length);
  const isStageMastered = averageStageMastery >= 80;

  // Handles evidence generated by any interactive module
  const handleRecordEvidence = React.useCallback(
    (
      conceptId: string,
      activityTitle: string,
      score: number,
      assessmentType: "practice" | "written" | "oral" = "practice",
      metadata?: Record<string, unknown>
    ) => {
      const evidence: AssessmentEvidence = {
        conceptId,
        assessmentType,
        score,
        metadata,
      };

      const result = masteryEngine.recordEvidence(evidence);
      const roundedScore = Math.round(result.newScore);

      setConceptScores((prev) => {
        const next = { ...prev, [conceptId]: roundedScore };
        const total = Object.values(next).reduce((a, b) => a + b, 0);
        const nextAvg = Math.round(total / stage1Concepts.length);
        if (nextAvg >= 80) {
          onStageCompleted?.(1, nextAvg);
        }
        return next;
      });

      setEvidenceLog((prev) => [
        {
          conceptId,
          activityTitle,
          score,
          timestamp: Date.now(),
          deltaText: `Score updated to ${roundedScore}% (${result.status}) via W-EMM`,
        },
        ...prev.slice(0, 4),
      ]);
    },
    [masteryEngine, onStageCompleted, stage1Concepts.length]
  );

  return (
    <div className="space-y-6">
      {/* Top Navigation & Breadcrumb Header */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 pb-4 border-b border-border/60">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <Button
              variant="ghost"
              size="sm"
              onClick={onBackToTopicPlan}
              className="h-7 px-2 text-xs gap-1 text-muted-foreground hover:text-foreground"
            >
              <ArrowLeft className="h-3.5 w-3.5" />
              Topic Overview
            </Button>
            <span className="text-muted-foreground/60 text-xs">•</span>
            <Badge variant="outline" className="font-mono text-[11px] border-emerald-500/40 text-emerald-400">
              Stage 1 of 5
            </Badge>
            <Badge variant="secondary" className="text-[11px]">
              Active Workspace
            </Badge>
          </div>

          <h2 className="text-xl sm:text-2xl font-bold text-foreground flex items-center gap-2">
            <Atom className="h-6 w-6 text-emerald-400" />
            Stage 1: Carbon Fundamentals
          </h2>
          <p className="text-xs text-muted-foreground">
            Explore tetravalency, catenation, bond multiplicity, and orbital geometry with interactive molecular manipulatives.
          </p>
        </div>

        {/* Stage Mastery Metric Dial */}
        <div className="w-full sm:w-auto p-3.5 rounded-xl border border-border/80 bg-card/70 flex flex-col items-start sm:items-end gap-1.5 min-w-[220px]">
          <div className="w-full flex items-center justify-between gap-4 text-xs font-mono">
            <span className="text-muted-foreground">Stage 1 Mastery (W-EMM)</span>
            <span
              className={`font-bold text-sm ${
                isStageMastered ? "text-emerald-400" : "text-foreground"
              }`}
            >
              {averageStageMastery}% / 80%
            </span>
          </div>

          <div className="w-full">
            <Progress value={averageStageMastery} className="h-2" />
          </div>

          <div className="w-full flex items-center justify-between text-[11px] text-muted-foreground">
            <span>Deterministic Threshold</span>
            <span>{isStageMastered ? "Prerequisite Satisfied" : "Unlocks Stage 2"}</span>
          </div>
        </div>
      </div>

      {/* Stage Mastery Unlocked Banner */}
      {isStageMastered && (
        <div className="p-4 rounded-xl border border-emerald-500/50 bg-emerald-950/30 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 animate-in fade-in duration-300">
          <div className="flex items-start gap-3">
            <div className="p-2 rounded-lg bg-emerald-500/20 text-emerald-400">
              <Trophy className="h-5 w-5" />
            </div>
            <div className="space-y-0.5">
              <h4 className="text-sm font-bold text-emerald-400">
                Stage 1 Prerequisite Satisfied ({averageStageMastery}% Mastery)!
              </h4>
              <p className="text-xs text-foreground/90">
                The KEA Deterministic Mastery Engine has validated your empirical evidence. Stage 2 (Hydrocarbon Foundations) is now unlocked in the Knowledge Graph DAG!
              </p>
            </div>
          </div>

          <Button
            size="sm"
            onClick={onBackToTopicPlan}
            className="bg-emerald-600 hover:bg-emerald-700 text-white font-semibold text-xs h-8 gap-1.5 shrink-0"
          >
            View Unlocked Route
            <ChevronRight className="h-3.5 w-3.5" />
          </Button>
        </div>
      )}

      {/* 5 Concept Navigation Tabs */}
      <div className="grid grid-cols-2 sm:grid-cols-5 gap-2">
        {stage1Concepts.map((concept, idx) => {
          const isSelected = activeConceptId === concept.id;
          const score = conceptScores[concept.id] || 0;
          const isMastered = score >= 80;

          const icons = [
            <Atom key="c1" className="h-4 w-4" />,
            <Link2 key="c2" className="h-4 w-4" />,
            <SplitSquareVertical key="c3" className="h-4 w-4" />,
            <Compass key="c4" className="h-4 w-4" />,
            <Hammer key="c5" className="h-4 w-4" />,
          ];

          return (
            <button
              key={concept.id}
              onClick={() => setActiveConceptId(concept.id)}
              className={`flex flex-col items-start p-3 rounded-xl border text-left transition-all ${
                isSelected
                  ? "border-emerald-500/70 bg-emerald-950/20 shadow-sm ring-1 ring-emerald-500/40"
                  : "border-border/60 bg-card hover:bg-muted/40 hover:border-border"
              }`}
            >
              <div className="w-full flex items-center justify-between mb-1.5">
                <span
                  className={`p-1.5 rounded-md ${
                    isSelected
                      ? "bg-emerald-500/20 text-emerald-400"
                      : "bg-muted text-muted-foreground"
                  }`}
                >
                  {icons[idx]}
                </span>
                <span
                  className={`text-[10px] font-mono px-1.5 py-0.5 rounded font-bold ${
                    isMastered
                      ? "bg-emerald-500/20 text-emerald-400 border border-emerald-500/30"
                      : score > 0
                      ? "bg-amber-500/20 text-amber-300"
                      : "bg-muted text-muted-foreground"
                  }`}
                >
                  {score}%
                </span>
              </div>

              <span className="text-xs font-semibold text-foreground line-clamp-1">
                {idx + 1}. {concept.name.split("&")[0].split(":")[0]}
              </span>
              <span className="text-[10px] text-muted-foreground mt-0.5 line-clamp-1">
                {concept.summary}
              </span>
            </button>
          );
        })}
      </div>

      {/* Main Active Visual Learning Module Display */}
      <div className="space-y-4">
        {activeConceptId === "c-org-1" && (
          <CarbonAtomVisualizer
            onEvidenceProduced={(score) =>
              handleRecordEvidence("c-org-1", "Why Carbon: Tetravalency", score, "practice")
            }
          />
        )}

        {activeConceptId === "c-org-2" && (
          <CarbonBondBuilder
            onEvidenceProduced={(score) =>
              handleRecordEvidence("c-org-2", "Catenation & Carbon Chains", score, "practice")
            }
          />
        )}

        {activeConceptId === "c-org-3" && (
          <BondOrderVisualizer
            onEvidenceProduced={(score) =>
              handleRecordEvidence("c-org-3", "Bond Multiplicity (Single/Double/Triple)", score, "practice")
            }
          />
        )}

        {activeConceptId === "c-org-4" && (
          <HybridizationVisualizer
            onEvidenceProduced={(score) =>
              handleRecordEvidence("c-org-4", "Orbital Hybridization & Geometry", score, "practice")
            }
          />
        )}

        {activeConceptId === "c-org-5" && (
          <MoleculeBuilder
            conceptId="c-org-5"
            onEvidenceProduced={(evidence: ChemistryLearningEvidence) =>
              handleRecordEvidence(
                "c-org-5",
                "Synthesis Challenge: Build Ethene",
                evidence.score,
                "practice",
                evidence.metadata
              )
            }
          />
        )}
      </div>

      {/* Live Evidence & Deterministic Mastery Audit Trail */}
      <Card className="border-border/60 bg-muted/15">
        <CardHeader className="py-3 px-4 border-b border-border/40">
          <div className="flex items-center justify-between">
            <CardTitle className="text-xs font-semibold text-foreground flex items-center gap-1.5 uppercase tracking-wider">
              <BrainCircuit className="h-3.5 w-3.5 text-primary" />
              Live Evidence Dispatch & W-EMM Audit Trail
            </CardTitle>
            <span className="text-[11px] font-mono text-muted-foreground">
              Deterministic Math • Zero LLM Score Hallucination
            </span>
          </div>
        </CardHeader>

        <CardContent className="p-4 space-y-2">
          {evidenceLog.length === 0 ? (
            <div className="text-xs text-muted-foreground py-2 text-center">
              Interact with the molecular modules above to produce verified learning evidence and update concept mastery.
            </div>
          ) : (
            <div className="space-y-1.5">
              {evidenceLog.map((log, i) => (
                <div
                  key={i}
                  className="flex items-center justify-between p-2 rounded bg-background/60 border border-border/50 text-xs"
                >
                  <div className="flex items-center gap-2">
                    <ShieldCheck className="h-3.5 w-3.5 text-emerald-400 shrink-0" />
                    <span className="font-semibold text-foreground">{log.activityTitle}</span>
                    <Badge variant="outline" className="text-[10px] font-mono">
                      {log.conceptId}
                    </Badge>
                  </div>
                  <span className="font-mono text-emerald-400 text-[11px]">{log.deltaText}</span>
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
